name: tradenote
services:
  tradenote:
    container_name: tradenote_app
    hostname: tradenote_app
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: tradenote:latest
    ports:
      - 4880:4880
    links:
      - mongo
    environment:
      MONGO_URI: mongodb://tradenote:tradenote@mongo:27017/tradenote?authSource=admin
      TRADENOTE_DATABASE: tradenote
      APP_ID: 123456
      MASTER_KEY: 123456
      TRADENOTE_PORT: 4880
  mongo:
    image: mongo:latest
    container_name: tradenote_db
    volumes:
      - tradenote_db:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: tradenote
      MONGO_INITDB_ROOT_PASSWORD: tradenote
      MONGO_INITDB_DATABASE: tradenote
volumes:
  tradenote_db:
    name: tradenote_db
